/**
 * Keyboard Plate - Generated by KLE-NG
 *
 * Cutout type: cherry-mx-basic
 * Stabilizer type: mx-basic
 * Plate thickness: 1.5 mm
 * Generated: 2026-06-21
 *
 * This file uses the @jscad/modeling API (OpenJSCAD v2).
 * Open with: https://openjscad.xyz/
 */
const jscad = require('@jscad/modeling')
const { polygon, roundedRectangle } = jscad.primitives
const { translate } = jscad.transforms
const { extrudeLinear } = jscad.extrusions
const { subtract, union } = jscad.booleans

const THICKNESS = 1.5 // mm

// --- Plate outline ---
const outline = translate([57.15, -39.1, 0], roundedRectangle({ size: [138.05, 101.95], roundRadius: 1 }))

// --- Shared shapes ---
const switch_shape = roundedRectangle({ size: [13.75, 13.75], roundRadius: 0.5 })
const stab_pad = roundedRectangle({ size: [6.75, 14.75], roundRadius: 0.5 })

// --- Switch cutouts ---
const switch_0 = switch_shape // "0,0" 1u
const switch_1 = translate([19.05, 0, 0], switch_shape) // "0,1" 1u
const switch_2 = translate([38.1, 0, 0], switch_shape) // "0,2" 1u
const switch_3 = translate([57.15, 0, 0], switch_shape) // "0,3" 1u
const switch_4 = translate([76.2, 0, 0], switch_shape) // "0,4" 1u
const switch_5 = translate([95.25, 0, 0], switch_shape) // "0,5" 1u
const switch_6 = translate([114.3, 0, 0], switch_shape) // "0,6" 1u
const switch_7 = translate([0, -19.05, 0], switch_shape) // "1,0" 1u
const switch_8 = translate([19.05, -19.05, 0], switch_shape) // "1,1" 1u
const switch_9 = translate([38.1, -19.05, 0], switch_shape) // "1,2" 1u
const switch_10 = translate([57.15, -19.05, 0], switch_shape) // "1,3" 1u
const switch_11 = translate([76.2, -19.05, 0], switch_shape) // "1,4" 1u
const switch_12 = translate([95.25, -19.05, 0], switch_shape) // "1,5" 1u
const switch_13 = translate([114.3, -19.05, 0], switch_shape) // "1,6" 1u
const switch_14 = translate([2.381, -38.1, 0], switch_shape) // "2,0" 1.25u
const switch_15 = translate([23.813, -38.1, 0], switch_shape) // "2,1" 1u
const switch_16 = translate([42.863, -38.1, 0], switch_shape) // "2,2" 1u
const switch_17 = translate([61.913, -38.1, 0], switch_shape) // "2,3" 1u
const switch_18 = translate([80.963, -38.1, 0], switch_shape) // "2,4" 1u
const switch_19 = translate([100.013, -38.1, 0], switch_shape) // "2,5" 1u
const switch_20 = translate([7.144, -57.15, 0], switch_shape) // "3,0" 1.75u
const switch_21 = translate([33.338, -57.15, 0], switch_shape) // "3,1" 1u
const switch_22 = translate([52.388, -57.15, 0], switch_shape) // "3,2" 1u
const switch_23 = translate([71.438, -57.15, 0], switch_shape) // "3,3" 1u
const switch_24 = translate([90.488, -57.15, 0], switch_shape) // "3,4" 1u
const switch_25 = translate([109.538, -57.15, 0], switch_shape) // "3,5" 1u
const switch_26 = translate([0, -76.2, 0], switch_shape) // "4,0" 1u
const switch_27 = translate([19.05, -76.2, 0], switch_shape) // "4,1" 1u
const switch_28 = translate([40.481, -76.2, 0], switch_shape) // "4,2" 1.25u
const switch_29 = translate([92.869, -76.2, 0], switch_shape) // "4,4" 2.75u

// --- Stabilizer cutouts ---
const stab_29_a = translate([80.931, -77.7, 0], stab_pad)
const stab_29_b = translate([104.807, -77.7, 0], stab_pad)
const stab_29 = union(stab_29_a, stab_29_b) // stabilizer for "4,4" (switch 29)

// --- Assembly ---
const allCutouts = union(
    switch_0,
    switch_1,
    switch_2,
    switch_3,
    switch_4,
    switch_5,
    switch_6,
    switch_7,
    switch_8,
    switch_9,
    switch_10,
    switch_11,
    switch_12,
    switch_13,
    switch_14,
    switch_15,
    switch_16,
    switch_17,
    switch_18,
    switch_19,
    switch_20,
    switch_21,
    switch_22,
    switch_23,
    switch_24,
    switch_25,
    switch_26,
    switch_27,
    switch_28,
    switch_29,
    stab_29,
)
const plate2d = subtract(outline, allCutouts)
const plate3d = extrudeLinear({ height: THICKNESS }, plate2d)
const finalPlate = plate3d

const main = () => finalPlate

module.exports = { main }
