/**
 * Keyboard Plate - Generated by KLE-NG
 *
 * Cutout type: cherry-mx-basic
 * Stabilizer type: mx-basic
 * Plate thickness: 1.5 mm
 * Generated: 2026-06-21
 *
 * This file uses the @jscad/modeling API (OpenJSCAD v2).
 * Open with: https://openjscad.xyz/
 */
const jscad = require('@jscad/modeling')
const { polygon, roundedRectangle } = jscad.primitives
const { translate } = jscad.transforms
const { extrudeLinear } = jscad.extrusions
const { subtract, union } = jscad.booleans

const THICKNESS = 1.5 // mm

// --- Plate outline ---
const outline = translate([66.675, -39.1, 0], roundedRectangle({ size: [157.1, 101.95], roundRadius: 1 }))

// --- Shared shapes ---
const switch_shape = roundedRectangle({ size: [13.75, 13.75], roundRadius: 0.5 })
const stab_pad = roundedRectangle({ size: [6.75, 14.75], roundRadius: 0.5 })

// --- Switch cutouts ---
const switch_0 = switch_shape // "0,0" 1u
const switch_1 = translate([19.05, 0, 0], switch_shape) // "0,1" 1u
const switch_2 = translate([38.1, 0, 0], switch_shape) // "0,2" 1u
const switch_3 = translate([57.15, 0, 0], switch_shape) // "0,3" 1u
const switch_4 = translate([76.2, 0, 0], switch_shape) // "0,4" 1u
const switch_5 = translate([95.25, 0, 0], switch_shape) // "0,5" 1u
const switch_6 = translate([114.3, 0, 0], switch_shape) // "0,6" 1u
const switch_7 = translate([133.35, 0, 0], switch_shape) // "0,7" 1u
const switch_8 = translate([9.525, -19.05, 0], switch_shape) // "1,0" 1u
const switch_9 = translate([28.575, -19.05, 0], switch_shape) // "1,1" 1u
const switch_10 = translate([47.625, -19.05, 0], switch_shape) // "1,2" 1u
const switch_11 = translate([66.675, -19.05, 0], switch_shape) // "1,3" 1u
const switch_12 = translate([85.725, -19.05, 0], switch_shape) // "1,4" 1u
const switch_13 = translate([104.775, -19.05, 0], switch_shape) // "1,5" 1u
const switch_14 = translate([128.588, -19.05, 0], switch_shape) // "1,6" 1.5u
const switch_15 = translate([14.288, -38.1, 0], switch_shape) // "2,0" 1u
const switch_16 = translate([33.338, -38.1, 0], switch_shape) // "2,1" 1u
const switch_17 = translate([52.388, -38.1, 0], switch_shape) // "2,2" 1u
const switch_18 = translate([71.438, -38.1, 0], switch_shape) // "2,3" 1u
const switch_19 = translate([90.488, -38.1, 0], switch_shape) // "2,4" 1u
const switch_20 = translate([109.538, -38.1, 0], switch_shape) // "2,5" 1u
const switch_21 = translate([130.969, -38.1, 0], switch_shape) // "2,6" 1.25u
const switch_22 = translate([0, -57.15, 0], switch_shape) // "3,0" 1u
const switch_23 = translate([19.05, -57.15, 0], switch_shape) // "3,1" 1u
const switch_24 = translate([38.1, -57.15, 0], switch_shape) // "3,2" 1u
const switch_25 = translate([57.15, -57.15, 0], switch_shape) // "3,3" 1u
const switch_26 = translate([76.2, -57.15, 0], switch_shape) // "3,4" 1u
const switch_27 = translate([95.25, -57.15, 0], switch_shape) // "3,5" 1u
const switch_28 = translate([123.825, -57.15, 0], switch_shape) // "3,6" 2u
const switch_29 = translate([16.669, -76.2, 0], switch_shape) // "4,0" 2.75u
const switch_30 = translate([54.769, -76.2, 0], switch_shape) // "4,2" 1.25u
const switch_31 = translate([76.2, -76.2, 0], switch_shape) // "4,4" 1u
const switch_32 = translate([95.25, -76.2, 0], switch_shape) // "4,5" 1u
const switch_33 = translate([114.3, -76.2, 0], switch_shape) // "4,6" 1u
const switch_34 = translate([133.35, -76.2, 0], switch_shape) // "4,7" 1u

// --- Stabilizer cutouts ---
const stab_28_a = translate([111.887, -58.65, 0], stab_pad)
const stab_28_b = translate([135.763, -58.65, 0], stab_pad)
const stab_28 = union(stab_28_a, stab_28_b) // stabilizer for "3,6" (switch 28)
const stab_29_a = translate([4.731, -77.7, 0], stab_pad)
const stab_29_b = translate([28.607, -77.7, 0], stab_pad)
const stab_29 = union(stab_29_a, stab_29_b) // stabilizer for "4,0" (switch 29)

// --- Assembly ---
const allCutouts = union(
    switch_0,
    switch_1,
    switch_2,
    switch_3,
    switch_4,
    switch_5,
    switch_6,
    switch_7,
    switch_8,
    switch_9,
    switch_10,
    switch_11,
    switch_12,
    switch_13,
    switch_14,
    switch_15,
    switch_16,
    switch_17,
    switch_18,
    switch_19,
    switch_20,
    switch_21,
    switch_22,
    switch_23,
    switch_24,
    switch_25,
    switch_26,
    switch_27,
    switch_28,
    stab_28,
    switch_29,
    stab_29,
    switch_30,
    switch_31,
    switch_32,
    switch_33,
    switch_34,
)
const plate2d = subtract(outline, allCutouts)
const plate3d = extrudeLinear({ height: THICKNESS }, plate2d)
const finalPlate = plate3d

const main = () => finalPlate

module.exports = { main }
