/**
 * Keyboard Plate - Generated by KLE-NG
 *
 * Cutout type: cherry-mx-basic
 * Stabilizer type: mx-basic
 * Plate thickness: 1.5 mm
 * Generated: 2026-06-27
 *
 * This file uses the @jscad/modeling API (OpenJSCAD v2).
 * Open with: https://openjscad.xyz/
 */
const jscad = require('@jscad/modeling')
const { polygon, roundedRectangle } = jscad.primitives
const { translate } = jscad.transforms
const { extrudeLinear } = jscad.extrusions
const { subtract, union } = jscad.booleans

const THICKNESS = 1.5 // mm

// --- Plate outline ---
const outline = translate([28.575, -39.1, 0], roundedRectangle({ size: [80.9, 101.95], roundRadius: 1 }))

// --- Shared shapes ---
const switch_shape = roundedRectangle({ size: [13.75, 13.75], roundRadius: 0.5 })
const stab_pad = roundedRectangle({ size: [6.75, 14.75], roundRadius: 0.5 })

// --- Switch cutouts ---
const switch_0 = switch_shape // "0,0" 1u
const switch_1 = translate([19.05, 0, 0], switch_shape) // "0,1" 1u
const switch_2 = translate([38.1, 0, 0], switch_shape) // "0,2" 1u
const switch_3 = translate([57.15, 0, 0], switch_shape) // "0,3" 1u
const switch_4 = translate([0, -19.05, 0], switch_shape) // "1,0" 1u
const switch_5 = translate([19.05, -19.05, 0], switch_shape) // "1,1" 1u
const switch_6 = translate([38.1, -19.05, 0], switch_shape) // "1,2" 1u
const switch_7 = translate([57.15, -19.05, 0], switch_shape) // "1,3" 1u
const switch_8 = translate([0, -38.1, 0], switch_shape) // "2,0" 1u
const switch_9 = translate([19.05, -38.1, 0], switch_shape) // "2,1" 1u
const switch_10 = translate([38.1, -38.1, 0], switch_shape) // "2,2" 1u
const switch_11 = translate([57.15, -38.1, 0], switch_shape) // "2,3" 1u
const switch_12 = translate([0, -57.15, 0], switch_shape) // "3,0" 1u
const switch_13 = translate([19.05, -57.15, 0], switch_shape) // "3,1" 1u
const switch_14 = translate([38.1, -57.15, 0], switch_shape) // "3,2" 1u
const switch_15 = translate([57.15, -57.15, 0], switch_shape) // "3,3" 1u
const switch_16 = translate([9.525, -76.2, 0], switch_shape) // "4,0" 2u
const switch_17 = translate([38.1, -76.2, 0], switch_shape) // "4,2" 1u
const switch_18 = translate([57.15, -76.2, 0], switch_shape) // "4,3" 1u

// --- Stabilizer cutouts ---
const stab_16_a = translate([-2.413, -77.7, 0], stab_pad)
const stab_16_b = translate([21.463, -77.7, 0], stab_pad)
const stab_16 = union(stab_16_a, stab_16_b) // stabilizer for "4,0" (switch 16)

// --- Assembly ---
const allCutouts = union(
    switch_0,
    switch_1,
    switch_2,
    switch_3,
    switch_4,
    switch_5,
    switch_6,
    switch_7,
    switch_8,
    switch_9,
    switch_10,
    switch_11,
    switch_12,
    switch_13,
    switch_14,
    switch_15,
    switch_16,
    stab_16,
    switch_17,
    switch_18,
)
const plate2d = subtract(outline, allCutouts)
const plate3d = extrudeLinear({ height: THICKNESS }, plate2d)
const finalPlate = plate3d

const main = () => finalPlate

module.exports = { main }
